OBAListView (remove IGListKit)
OneBusAway/OBAKit pull request #304
Opened 2020-10-04 18:53 UTC by ualch9

Displays information as a vertical-scrolling list, a la TableView.

There are two separate `OBAListViewConfigurator`s under-the-hood. One is for iOS 14+, the other is for iOS 13.  iOS 14 uses `UICollectionLayoutListConfiguration` because its user experience is much better than our custom table view-like implementation.

## Todo
- [ ] Rows with custom views
- [ ] Cell actions (on tap, swipe, etc.)
- [ ] Collapsible headers
- [ ] Default rows UI (iOS 13)
- [ ] Section header styling (iOS 13)

## Goal
iOS 13 users get the same user experience as using IGListKit and iOS 14 users will \~automagically\~ get the upgraded experience.

| Collection View (iOS 13) - Fade animation | Collection View (iOS 14) - Cell moves animation |
| -------- | --------- |
 | ![](https://user-images.githubusercontent.com/22162410/94495505-d7b38f00-01a6-11eb-8e4f-40691b2a2828.gif) | ![](https://user-images.githubusercontent.com/22162410/94495511-db471600-01a6-11eb-9610-ffe1b0f1aa39.gif) |

## How it looks right now
```swift
struct Person: OBAListViewItem {
    var name: String
    var address: String

    func listViewConfigurationForThisItem(_ listView: OBAListView) -> OBAListContentConfiguration {
        return OBAListContentConfiguration(image: UIImage(systemName: "person.fill"), text: name, secondaryText: address, appearance: .subtitle, accessoryType: .none)
    }
}

class PersonsListView: OBAListView {
    override func sectionsForList() -> [OBAListViewSection] {
        [
            OBAListViewSection(id: "1", title: "B", contents: [
                Person(name: "Bo", address: "123 Main St"),
                Person(name: "Bob", address: "456 Broadway"),
                Person(name: "Bobby", address: "asdfasdkfjad")
            ]),
            OBAListViewSection(id: "2", title: "C", contents: [
                Person(name: "Ca", address: "193 Lochmere Ln"),
                Person(name: "Cab", address: "anywhere u want"),
                Person(name: "Cabby", address: "huh")
            ])
        ]
    }
}
```

| iOS 13 | iOS 14 |
| -------- | --------- |
 | ![](https://user-images.githubusercontent.com/22162410/95024138-11b4e300-0636-11eb-84ff-aa5aa17b7032.png) | ![](https://user-images.githubusercontent.com/22162410/95024139-12e61000-0636-11eb-9d40-8ac28305e5c1.png) |

UI work is needed for iOS 13.

Fixes #290

2020-10-09 22:23 UTC, ualch9 commented
Decided to scrap the idea of using UICollectionLayoutListConfiguration for iOS 14, I'm concerned that the multi-platform implementation will be too messy to maintain.

| Collapsed sections | Sticky header |
| --- | --- |
| ![IMG_1686](https://user-images.githubusercontent.com/22162410/95636151-37c9f100-0a43-11eb-80ac-e3afc5def029.PNG) | ![IMG_1687](https://user-images.githubusercontent.com/22162410/95636149-35679700-0a43-11eb-9745-884ac5af0654.PNG) |

2020-10-12 21:23 UTC, aaronbrethorst commented
🎉 I'll review soon!

2020-10-12 21:26 UTC, ualch9 commented
![](https://user-images.githubusercontent.com/22162410/95791723-cf734d80-0c96-11eb-968a-c0599e7e84a8.gif)

2020-10-12 21:55 UTC, ualch9 commented
@aaronbrethorst, made a quick naming change just now.

2020-10-24 08:49 UTC, ualch9 commented
There is a potential flaw with how I've written `createLayout()` when it comes to sections with no headers. Sections with `nil` titles will still display a header, which it shouldn't.

2020-10-24 18:52 UTC, aaronbrethorst commented
@ualch9 I finally have time to review this! Sorry it's taken me so long! Can you rebase against `master`?

2020-10-25 00:23 UTC, aaronbrethorst commented
I'm seeing a couple dozen SwiftLint issues. Can you install it and make sure to clean those up? (instructions are in the README)

2020-10-25 00:24 UTC, aaronbrethorst commented
Also, you'll want to add `type_name` to the list of Swiftlint's disabled rules.

```
disabled_rules:
  - function_parameter_count
  - identifier_name
  - statement_position
  - line_length
  - todo
  - private_over_fileprivate
  - type_name

```

2020-10-25 20:24 UTC, aaronbrethorst requested changes
This is looking really good! I'm seeing a crash on the Agency Alerts controller that'll need to get sorted out, plus I'd love to see a few more doc comments added while things are still fresh in your mind, but otherwise that's about it! Thanks for pulling this together!

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Alerts/AgencyAlertsViewController.swift
> +        self.reloadServerData()
remove `self.` here and elsewhere whenever possible.

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Alerts/AgencyAlertViewModel.swift
> +    struct ListViewModel: OBAListViewItem {
please add a one sentence doc comment to this.

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Helpers/OBAListViewDebug.swift
> +#if DEBUG
please add a one sentence comment to this file to explain what the structs and classes in it are for.

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Helpers/ReuseIdentifierProviding.swift
> +public protocol ReuseIdentifierProviding: UICollectionViewCell {
please add a one sentence doc comment to this.

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/OBAContentView.swift
> +/// The requirements for a content view that you create using a configuration.
Can you elaborate on where an `OBAContentView`-conforming object would be used? Doesn't have to be a ton of detail, but say something like "these content views are used in our list views for blah blah blah"

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/OBAListRowConfiguration.swift
> +public struct OBAListRowConfiguration: OBAContentConfiguration, Hashable, Equatable {
please add a one sentence doc comment to this

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/OBAListRowViewDefault.swift
> +    static let ReuseIdentifier: String = "OBAListRowViewDefault_ReuseIdentifier"
this explicit type can be removed

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/OBAListRowViewDefault.swift
> +    public struct DefaultViewModel: OBAListViewItem {
Can you add a one sentence doc comment to this?

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/OBAListRowViewHeader.swift
> +public class OBAListRowViewHeader: OBAListRowView {
can you add a one sentence doc comment to this?

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/OBAListRowViewSubtitle.swift
> +public class OBAListRowViewSubtitle: OBAListRowView {
can you add a one sentence doc comment to this?

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/OBAListRowViewValue.swift
> +public class OBAListRowViewValue: OBAListRowView {
can you add a one sentence doc comment to this?

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/SupplementaryViews/OBAListViewHeaderSupplementaryView.swift
> +public class OBAListRowHeaderSupplementaryView: UICollectionReusableView {
can you add a one sentence doc comment to this?

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/SupplementaryViews/OBAListViewSeparatorSupplementaryView.swift
> +/// A footer view displaying a separator line. Useful for faking a cell row collapse animation.
👍

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/ViewModels/OBAListViewAction.swift
> +    public var textColor: UIColor = .white
please pull these two colors into ThemeColors

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/ViewModels/OBAListViewSection.swift
> +public struct OBAListViewSection: Hashable {
can you add a one sentence doc comment to this?

2020-10-25 20:24 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/ViewModels/OBAListViewSection.swift
> +struct OBAListViewSectionHeader: OBAListViewItem {
can you add a one sentence doc comment to this?

2020-10-25 22:32 UTC, ualch9 commented on OBAKit/Alerts/AgencyAlertsViewController.swift
>  class AgencyAlertsViewController: UIViewController,
I've randomly encountered this before, but haven't been able to reliably reproduce when debugging. I've implemented a potential fix.

2020-10-26 02:42 UTC, aaronbrethorst approved these changes
🎉 I think this is good to go! nice work!!

2020-10-26 02:46 UTC, merged