OBAListView iOS 14 list
OneBusAway/OBAKit pull request #391
Opened 2021-06-15 16:59 UTC by ualch9

draft pr for ci.

2021-06-21 16:41 UTC, ualch9 commented
just noticed memory leaks. needs investigation but i think it's caused by listview caching data snapshots.

![image](https://user-images.githubusercontent.com/22162410/122797538-6c4da800-d274-11eb-8f81-c374562443cc.png)

2021-06-21 18:52 UTC, ualch9 commented
memory leak not related to this pr, opened #394

2021-06-23 18:36 UTC, aaronbrethorst requested changes
This looks like a great improvement! I noticed a couple of outstanding TODOs that you'd added that look like they still need to be taken care of. If you want to add issues for those and have me merge this, np. Otherwise let me know when they're wrapped up and I'll get this merged.

2021-06-23 18:36 UTC, aaronbrethorst commented on OBAKit/Bookmarks/TripBookmarkCell.swift
> -        fixiOS13AutoLayoutBug()
🎉

2021-06-23 18:36 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/OBAListView.swift
> +            // #398 - list view separators always appears on iOS 14.4
I like that you opened a task for this!

2021-06-23 18:36 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/OBAListView.swift
> +//        DispatchQueue.main.async {
delete me!

2021-06-23 18:36 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/Rows/OBAListRowConfiguration.swift
> +            case .detailButton: return .label(text: "i") // TODO: this
?

2021-06-23 18:36 UTC, aaronbrethorst commented on OBAKit/Stops/Sections/StopArrival/StopArrivalCell.swift
> +        // TODO: me!
todo!

2021-06-24 04:48 UTC, ualch9 commented on OBAKit/Stops/Sections/StopArrival/StopArrivalCell.swift
> +        // TODO: me!
opened #401

2021-06-25 02:44 UTC, aaronbrethorst approved these changes
:shipit: nice work

2021-06-25 02:45 UTC, merged