Various tweaks
OneBusAway/OBAKit pull request #407
Opened 2021-07-03 17:24 UTC by ualch9

## App-wide
- Allow DepartureTimeBadge to resize font size to fit width (fixes #354)
- Add context menus to `StopViewModel` instances (`MapFloatingPanelController` and `RecentStopsViewController`)

## TripViewController
- Don’t need to include user’s location when previewing TripViewController (fixes #366)
- Remove center on stop when user selects annotation

## DRY `StopViewModel`
- Remove `RecentStopViewModel`
- Removes reference to `Stop` instance in favor of the Stop's ID.
- Add display route icons to stop rows
- Don’t show stop subtitle if the routes are all empty strings ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-27 at 10 40 40](https://user-images.githubusercontent.com/22162410/124362214-76fb2c00-dbe8-11eb-881c-2ba86f3657ab.png)

## Other
- Add empty data set for Alerts ![Simulator Screen Shot - iPhone 12 Pro - 2021-07-01 at 00 21 34](https://user-images.githubusercontent.com/22162410/124362211-75316880-dbe8-11eb-9be6-fbf4ed441537.png)
- Add delete contextual action to OBAListView (a #391 regression)

## Tech
- Adds `OBAImageViewConfiguration` for configuring a UIListContentConfiguration's image view
- Adds SwiftUI view previews to `TripSegmentView` ![image](https://user-images.githubusercontent.com/22162410/124362248-ae69d880-dbe8-11eb-9182-3abfed99a763.png)

2021-07-04 05:14 UTC, aaronbrethorst commented on OBAKit/Controls/ListView/OBAListView.swift
> +            let isCellCompact = cellSize < 64
👍

2021-07-04 05:15 UTC, aaronbrethorst requested changes
Generally looks great! Can you take a look at the CI failure? Looks like a legit issue as opposed to spurious noise.

2021-07-05 15:57 UTC, ualch9 commented
> Generally looks great! Can you take a look at the CI failure? Looks like a legit issue as opposed to spurious noise.

Fixed in fc9d810, seems to be a Xcode 12.4 Swift 5.3 "feature"

2021-07-05 17:45 UTC, merged

2021-07-05 17:45 UTC, aaronbrethorst reviewed
👍